#!/bin/sh
### BEGIN INIT INFO
# Provides:          go-pod-provisioning
# Required-Start:    $network $remote_fs $syslog
# Required-Stop:     $network $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start Pod Provisioning Service at boot time
# Description:       Enable Pod Provisioning service running on port 24070.
### END INIT INFO

DAEMON=/usr/bin/go-pod-provisioning
NAME=go-pod-provisioning
DESC="Pod Provisioning Service"
PIDFILE=/var/run/$NAME.pid
LOGFILE=/var/log/$NAME.log

DAEMON_PROXY=/usr/bin/proxy-server
LOGFILE_PROXY=/tmp/proxy.log
PIDFILE_PROXY=/var/run/proxy.pid


start_proxy() {
    echo -n "Starting attested TLS Proxy: "
    start-stop-daemon -S -p $PIDFILE_PROXY -N -10 -b -a /bin/sh -- -c "exec 
        ${DAEMON_PROXY} --listen-addr=0.0.0.0:24071 --target-addr=http://localhost:24070 --server-attestation-type dcap-tdx \
        2>&1 | tee ${LOGFILE_PROXY}"
    echo "proxy."
}

start() {
  # Start the attested TLS reverse proxy server
  start_proxy

    echo -n "Starting $DESC: "
    echo "Starting $DESC" > /var/volatile/system-api.fifo

    start-stop-daemon -S --make-pidfile -p $PIDFILE -m -b -a $DAEMON -- $DAEMON_ARGS > $LOGFILE 2>&1
    echo "$NAME."
}

stop() {
    echo -n "Stopping $DESC: "
    echo "Stopping $DESC" > /var/volatile/system-api.fifo
    start-stop-daemon --stop --quiet --pidfile $PIDFILE
    rm -f $PIDFILE
    echo "$NAME."
}

restart() {
    echo "Restarting $DESC: "
    echo "Restarting $DESC" > /var/volatile/system-api.fifo
    stop
    sleep 1
    start
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart|force-reload)
        restart
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|force-reload}" >&2
        exit 1
        ;;
esac

exit 0

